# Request
string launch_file
string launch_package

TopicData[] topics

string[] arg_keys
string[] arg_values
---
# Result
int32 pid
---
# Feedback
int32 completed_topics
int32 expected_topics
string[] uncompleted_topic_names